
# Build matrix
language: node_js
matrix:
  include:

    # Run lint only in Node.js 0.12
    - node_js: '0.12'
      env: LINT=true

    # Test in Node.js 0.10+
    - node_js: '0.10'
    - node_js: '0.12'
    - node_js: '4'
    - node_js: '5'

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - 'if [ $LINT ]; then make verify; fi'
  - 'if [ ! $LINT ]; then make test; fi'
